Repository crustio/crust, pull requests merged in 2020-11, with the labels that each got.

#304 [Candy] Support bonding ETH address
  Cargo.lock
  cstrml/candy/Cargo.toml
  cstrml/candy/src/lib.rs
Labels: A4-enhancement, need-cherry-block🍒

#309 [GPoS] Remove random selection
  cstrml/staking/src/lib.rs
  cstrml/staking/src/tests.rs
Labels: need-cherry-block🍒

#315 [MPoW] Transfer A's report in slot to B during AB upgrade process
  cstrml/swork/src/lib.rs
  cstrml/swork/src/tests.rs
Labels: P0-dropeverything🔔, need-cherry-block🍒

#316 [Runtime] Change sPower ratio
  runtime/src/lib.rs
Labels: M0-protocol

#319 [Dockerize] Fix crust env dockerfile
  docker/crust-env/Dockerfile
  docker/crust/Dockerfile
  docker/rust-toolchain
  runtime/Cargo.toml
Labels: A4-enhancement, I2-bug 🐜, need-cherry-block🍒

#320 [Docs] Update docker readme
  docker/README.md
Labels: I5-documentation 📄

#328 [GPoS] Decrease SPowerRatio to 10
  runtime/src/lib.rs
Labels: need-cherry-block🍒
