Repository crustio/crust, pull requests merged in 2020-08, with the labels that each got.

#212 [Client] Add more bootnodes to maxwell genesis json
  node/res/maxwell.json
Labels: enhancement, maxwell

#230 [Market+MPoW] Unify glossary
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  README.md
  cstrml/market/Cargo.toml
  cstrml/market/src/lib.rs
  cstrml/market/src/mock.rs
  cstrml/market/src/tests.rs
  cstrml/payment/Cargo.toml
  cstrml/payment/src/lib.rs
  cstrml/payment/src/mock.rs
  cstrml/payment/src/tests.rs
  cstrml/staking/Cargo.toml
  cstrml/staking/src/lib.rs
  cstrml/staking/src/mock.rs
  cstrml/swork/Cargo.toml
  cstrml/swork/src/api.rs
  cstrml/swork/src/lib.rs
  cstrml/swork/src/mock.rs
  cstrml/swork/src/tests.rs
  docs/CONTRIBUTION.md
  node/Cargo.toml
  node/res/maxwell.json
  node/res/rocky.json
  node/src/chain_spec.rs
  node/src/service.rs
  primitives/src/constants.rs
  primitives/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: A2-breakapi

#232 [ChainSpec] Change bootnodes
  node/res/maxwell.json
Labels: A5-insubstantial

#234 [Client] Upgrade into rc5
  .github/workflows/rust.yml
  Cargo.lock
  cstrml/balances/Cargo.toml
  cstrml/balances/src/benchmarking.rs
  cstrml/balances/src/default_weight.rs
  cstrml/balances/src/lib.rs
  cstrml/balances/src/tests.rs
  cstrml/balances/src/tests_composite.rs
  cstrml/balances/src/tests_local.rs
  cstrml/market/Cargo.toml
  cstrml/market/src/lib.rs
  cstrml/market/src/mock.rs
  cstrml/payment/Cargo.toml
  cstrml/payment/src/lib.rs
  cstrml/payment/src/mock.rs
  cstrml/staking/Cargo.toml
  cstrml/staking/src/lib.rs
  cstrml/staking/src/mock.rs
  cstrml/swork/Cargo.toml
  cstrml/swork/src/lib.rs
  cstrml/swork/src/mock.rs
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/command.rs
  node/src/service.rs
  primitives/Cargo.toml
  runtime/Cargo.toml
  runtime/build.rs
  runtime/src/lib.rs
Labels: A1-maybeforked, A4-enhancement, M1-performance, P0-dropeverything🔔

#236 [GPoS] New Reward Mechanism
  cstrml/staking/src/lib.rs
  cstrml/staking/src/mock.rs
  cstrml/staking/src/tests.rs
Labels: A1-maybeforked, A3-breaktest, M0-protocol, P0-dropeverything🔔

#240 [Runtime] Add treasury into runtime
  Cargo.lock
  node/src/chain_spec.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: A4-enhancement, M0-protocol

#246 [GPoS] Remove active check
  cstrml/staking/src/lib.rs
  cstrml/staking/src/tests.rs
Labels: A3-breaktest, A4-enhancement, M0-protocol

#239 [Benchmark] Support benchmark for Swork, Staking, Market and Balances
  Cargo.lock
  cstrml/balances/src/benchmarking.rs
  cstrml/market/Cargo.toml
  cstrml/market/src/benchmarking.rs
  cstrml/market/src/lib.rs
  cstrml/staking/Cargo.toml
  cstrml/staking/src/benchmarking.rs
  cstrml/staking/src/lib.rs
  cstrml/swork/Cargo.toml
  cstrml/swork/src/benchmarking.rs
  cstrml/swork/src/lib.rs
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  node/src/executor.rs
  node/src/main.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: A4-enhancement, M2-nicetohave

#244 [Market] Support directory
  cstrml/market/src/lib.rs
  cstrml/market/src/tests.rs
  cstrml/payment/src/tests.rs
  primitives/src/lib.rs
Labels: A4-enhancement, M0-protocol, P1-asap🏃🏼‍♂️

#247 Prepping 0.8.0
  Cargo.lock
  cstrml/balances/Cargo.toml
  cstrml/market/Cargo.toml
  cstrml/payment/Cargo.toml
  cstrml/staking/Cargo.toml
  cstrml/swork/Cargo.toml
  node/Cargo.toml
  node/res/maxwell.json
  primitives/Cargo.toml
  runtime/Cargo.toml
Labels: P1-asap🏃🏼‍♂️

#248 [Hotfix] Fix guarantee and cc2 chain spec
  cstrml/staking/src/lib.rs
  node/res/maxwell.json
Labels: I1-panic 😱, P0-dropeverything🔔
