Repository crustio/crust, pull requests merged in 2020-07, with the labels that each got.

#179 [Market] Change Sorder price into provider side
  cstrml/market/src/lib.rs
  cstrml/market/src/mock.rs
  cstrml/market/src/tests.rs
  cstrml/payment/src/lib.rs
  cstrml/payment/src/mock.rs
  cstrml/payment/src/tests.rs
  cstrml/tee/src/api.rs
  cstrml/tee/src/mock.rs
  runtime/src/lib.rs
Labels: breaksapi, maxwell, pleasereview

#170 [Market] Add market punishing mechanism
  cstrml/market/src/lib.rs
  cstrml/market/src/mock.rs
  cstrml/market/src/tests.rs
  cstrml/payment/src/mock.rs
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  runtime/src/lib.rs
Labels: maxwell, pleasereview

#181 [MPoW] Add AB Upgrade
  cstrml/market/src/mock.rs
  cstrml/payment/src/mock.rs
  cstrml/staking/src/mock.rs
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  cstrml/tee/src/tests.rs
  node/src/chain_spec.rs
Labels: breaksapi, maxwell, pleasereview

#183 [Upgrade] Upgrade substrate rc4
  Cargo.lock
  cstrml/balances/Cargo.toml
  cstrml/balances/src/lib.rs
  cstrml/balances/src/tests.rs
  cstrml/balances/src/tests_composite.rs
  cstrml/balances/src/tests_local.rs
  cstrml/market/Cargo.toml
  cstrml/market/src/mock.rs
  cstrml/payment/Cargo.toml
  cstrml/payment/src/mock.rs
  cstrml/staking/Cargo.toml
  cstrml/staking/src/inflation.rs
  cstrml/staking/src/lib.rs
  cstrml/staking/src/mock.rs
  cstrml/staking/src/tests.rs
  cstrml/tee/Cargo.toml
  cstrml/tee/src/mock.rs
  cstrml/tee/src/tests.rs
  node/Cargo.toml
  node/src/lib.rs
  node/src/service.rs
  primitives/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: maxwell, maybeforked, pleasereview

#177 [Payment] New slot pay menchanism
  Cargo.lock
  cstrml/market/src/lib.rs
  cstrml/payment/Cargo.toml
  cstrml/payment/src/lib.rs
  cstrml/payment/src/mock.rs
  cstrml/payment/src/tests.rs
  cstrml/tee/src/lib.rs
  runtime/src/lib.rs
Labels: maxwell, pleasereview

#184 [Client] Add rocky genesis spec
  Cargo.lock
  cstrml/market/src/lib.rs
  node/Cargo.toml
  node/res/rocky.json
  node/src/chain_spec.rs
  node/src/command.rs
Labels: enhancement, maxwell, pleasereview

#187 [MPoW] Remodule tee
  cstrml/market/src/mock.rs
  cstrml/payment/src/mock.rs
  cstrml/payment/src/tests.rs
  cstrml/staking/src/mock.rs
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  cstrml/tee/src/tests.rs
  node/res/rocky.json
  node/src/chain_spec.rs
Labels: breaksapi, enhancement, maxwell, pleasereview

#190 [MPoW] Merged work report
  cstrml/market/src/mock.rs
  cstrml/payment/src/mock.rs
  cstrml/staking/src/mock.rs
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  cstrml/tee/src/tests.rs
  node/src/chain_spec.rs
Labels: breaksapi, maxwell, p0, pleasereview

#191 [MPoW] Add AB Upgrade tests
  cstrml/tee/src/lib.rs
  cstrml/tee/src/tests.rs
Labels: enhancement, maxwell, p0, pleasereview

#189 [Client] Dockerize
  .gitignore
  README.md
  docker/Cargo.config
  docker/README.md
  docker/build.sh
  docker/build_bin.sh
  docker/build_env.sh
  docker/crust-env/Dockerfile
  docker/crust/Dockerfile
  docker/crust/run.sh
  docker/rust-toolchain
  docker/utils.sh
Labels: enhancement, maxwell, pleasereview

#193 [GPoS] Improve reward event
  cstrml/staking/src/lib.rs
  docker/README.md
Labels: documentation, enhancement, maxwell, pleasereview

#194 [MPoW] Fix register cannot update
  cstrml/tee/src/lib.rs
Labels: maxwell🐜, p0, pleasereview

#196 [Market] Fix outdated sorder not close
  cstrml/market/src/lib.rs
  cstrml/market/src/tests.rs
  cstrml/payment/src/lib.rs
  cstrml/staking/src/lib.rs
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  cstrml/tee/src/tests.rs
Labels: maxwell🐜, p0, pleasereview

#197 Optimize crust runtime construction
  Cargo.lock
  cstrml/balances/Cargo.toml
  cstrml/market/Cargo.toml
  cstrml/payment/Cargo.toml
  cstrml/staking/Cargo.toml
  cstrml/tee/Cargo.toml
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/Cargo.toml
  runtime/src/impls.rs
  runtime/src/lib.rs
Labels: enhancement, maxwell, pleasereview

#199 [Payment] Fix payment slot factor
  cstrml/market/src/lib.rs
  cstrml/payment/src/lib.rs
  cstrml/payment/src/tests.rs
Labels: maxwell🐜, p0, pleasereview

#200 [Docs] Update README
  README.md
Labels: documentation

#203 [GPoS] Change stake limit calculation strategy
  cstrml/staking/src/lib.rs
  cstrml/staking/src/mock.rs
  cstrml/staking/src/tests.rs
  runtime/src/lib.rs
Labels: breaktest, maxwell, p0, pleasereview

#204 [Params] Change maxwell on-chain params
  cstrml/market/src/lib.rs
  cstrml/staking/src/lib.rs
  cstrml/tee/src/lib.rs
  runtime/src/lib.rs
Labels: maxwell, pleasereview

#205 [Upgrade] Prepping 0.7.0
  Cargo.lock
  cstrml/balances/Cargo.toml
  cstrml/market/Cargo.toml
  cstrml/payment/Cargo.toml
  cstrml/staking/Cargo.toml
  cstrml/tee/Cargo.toml
  node/Cargo.toml
  node/res/maxwell.json
  node/src/chain_spec.rs
  node/src/command.rs
  primitives/Cargo.toml
  runtime/Cargo.toml
Labels: maxwell, pleasereview

#206 [Upgrade] Update rocky wasm and maxwell bootnodes
  node/res/maxwell.json
  node/res/rocky.json
Labels: maxwell, pleasereview

#207 [GPoS] Fix reward event
  cstrml/staking/src/lib.rs
Labels: maxwell🐜, pleasereview

#208 [MPoW+Market] Fix set failed sorder status
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  cstrml/tee/src/tests.rs
Labels: maxwell🐜, p0, pleasereview

#209 [Docs] Change readme and a comment
  README.md
  cstrml/tee/src/lib.rs
Labels: documentation
