Repository crustio/crust, pull requests merged in 2020-05, with the labels that each got.

#121 [Market] change market code
  cstrml/market/src/lib.rs
  cstrml/market/src/tests.rs
  cstrml/tee/src/lib.rs
Labels: betanet, breaksapi

#117 New guarantee mechanism
  cstrml/staking/src/lib.rs
  cstrml/staking/src/mock.rs
  cstrml/staking/src/tests.rs
Labels: betanet, breaksapi, enhancement

#126 [Market] reconstruct market and tee's relationship
  Cargo.lock
  cstrml/market/Cargo.toml
  cstrml/market/src/lib.rs
  cstrml/market/src/mock.rs
  cstrml/market/src/tests.rs
  cstrml/staking/src/lib.rs
  cstrml/staking/src/mock.rs
  cstrml/tee/Cargo.toml
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  primitives/src/lib.rs
  runtime/src/lib.rs
Labels: betanet, breaksapi, pleasereview

#127 [Market] Change provision
  cstrml/market/src/lib.rs
  cstrml/market/src/mock.rs
  cstrml/market/src/tests.rs
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
Labels: betanet, breaksapi, pleasereview

#128 [MPoW] Change work report
  cstrml/market/src/mock.rs
  cstrml/staking/src/mock.rs
  cstrml/tee/Cargo.toml
  cstrml/tee/src/api.rs
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  cstrml/tee/src/tests.rs
  node/src/chain_spec.rs
Labels: betanet, breaksapi, pleasereview

#130 [Market+MPoW] Add active check on work report
  cstrml/market/src/lib.rs
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  cstrml/tee/src/tests.rs
Labels: betanet, breaksconsensus, pleasereview

#131 [Market+MPoW] Add passive check from storage order
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  cstrml/tee/src/tests.rs
Labels: betanet, breaksconsensus, pleasereview

#132 [Market] Solve random order id
  cstrml/market/src/lib.rs
  cstrml/market/src/mock.rs
  cstrml/market/src/tests.rs
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  cstrml/tee/src/tests.rs
  runtime/src/lib.rs
Labels: betanet🐜, breaksapi, breaksconsensus, pleasereview

#133 [Market] Change address for conflicting at API side
  cstrml/market/src/lib.rs
  cstrml/market/src/tests.rs
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  primitives/src/lib.rs
  runtime/src/lib.rs
Labels: betanet, breaksapi, pleasereview

#139 [Market] Folk balances into our repo and replace pallet balances to balances in runtime and staking
  .github/workflows/rust.yml
  Cargo.lock
  cstrml/balances/Cargo.toml
  cstrml/balances/src/benchmarking.rs
  cstrml/balances/src/lib.rs
  cstrml/balances/src/tests.rs
  cstrml/balances/src/tests_composite.rs
  cstrml/balances/src/tests_local.rs
  cstrml/staking/Cargo.toml
  cstrml/staking/src/mock.rs
  runtime/Cargo.toml
Labels: maxwell

#140 [MPoW] Fix updating stake limit on reporting works
  cstrml/tee/src/lib.rs
Labels: maxwell

#142 [Market] add completed_on in storage order for delay payment and fix a potential bug
  cstrml/market/src/lib.rs
  cstrml/market/src/tests.rs
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  cstrml/tee/src/tests.rs
Labels: breaksapi, maxwell, pleasereview, rocky, rocky🐜

#146 Upgrade substrate to rc2 and delete customized balances
  .github/workflows/rust.yml
  Cargo.lock
  cstrml/balances/Cargo.toml
  cstrml/balances/src/benchmarking.rs
  cstrml/balances/src/lib.rs
  cstrml/balances/src/tests.rs
  cstrml/balances/src/tests_composite.rs
  cstrml/balances/src/tests_local.rs
  cstrml/market/Cargo.toml
  cstrml/market/src/lib.rs
  cstrml/market/src/mock.rs
  cstrml/staking/Cargo.toml
  cstrml/staking/src/lib.rs
  cstrml/staking/src/mock.rs
  cstrml/tee/Cargo.toml
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  node/Cargo.toml
  node/src/service.rs
  primitives/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: maxwell, pleasereview
