Repository crustio/crust, pull requests merged in 2020-09, with the labels that each got.

#249 [Upgrade] Prepping 0.8.0
  cstrml/staking/src/lib.rs
  cstrml/staking/src/tests.rs
  node/res/maxwell.json
Labels: A3-breaktest, M0-protocol, P0-dropeverything🔔

#251 [Upgrade] Upgrade into rc6
  Cargo.lock
  Cargo.toml
  cstrml/balances/Cargo.toml
  cstrml/market/Cargo.toml
  cstrml/payment/Cargo.toml
  cstrml/staking/Cargo.toml
  cstrml/swork/Cargo.toml
  node/Cargo.toml
  node/src/command.rs
  node/src/service.rs
  primitives/Cargo.toml
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: A1-maybeforked, A4-enhancement, P1-asap🏃🏼‍♂️

#252 [GPoS] Support active era
  cstrml/staking/src/lib.rs
  cstrml/staking/src/mock.rs
  cstrml/staking/src/tests.rs
  runtime/src/lib.rs
Labels: A0-breakconsensus, M0-protocol, P1-asap🏃🏼‍♂️

#256 [Runtime] Add utility and identity
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/weights/mod.rs
  runtime/src/weights/pallet_utility.rs
Labels: A4-enhancement

#255 [Benchmark] Fix it and add one more test
  cstrml/market/src/benchmarking.rs
  runtime/src/lib.rs
Labels: A4-enhancement, M1-performance

#257 [Runtime] Refine pallets name
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/command.rs
  node/src/service.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/weights/pallet_utility.rs
Labels: A4-enhancement

#258 [GPoS] support MaxGuarantorRewardedPerValidator
  cstrml/staking/src/lib.rs
  cstrml/staking/src/mock.rs
  cstrml/staking/src/tests.rs
  runtime/src/lib.rs
Labels: A4-enhancement, M0-protocol

#261 [MPoW] New MPoW
  .github/workflows/rust.yml
  cstrml/market/src/mock.rs
  cstrml/market/src/tests.rs
  cstrml/payment/src/mock.rs
  cstrml/payment/src/tests.rs
  cstrml/staking/src/lib.rs
  cstrml/staking/src/mock.rs
  cstrml/swork/src/api.rs
  cstrml/swork/src/benchmarking.rs
  cstrml/swork/src/lib.rs
  cstrml/swork/src/mock.rs
  cstrml/swork/src/tests.rs
  node/src/chain_spec.rs
  runtime/src/lib.rs
Labels: A0-breakconsensus, A3-breaktest, M0-protocol, P0-dropeverything🔔

#264 Upgrade to substrate stable v2.0.0 🎉
  Cargo.lock
  cstrml/balances/Cargo.toml
  cstrml/balances/src/benchmarking.rs
  cstrml/balances/src/lib.rs
  cstrml/balances/src/tests_composite.rs
  cstrml/balances/src/tests_local.rs
  cstrml/market/Cargo.toml
  cstrml/market/src/mock.rs
  cstrml/payment/Cargo.toml
  cstrml/payment/src/mock.rs
  cstrml/staking/Cargo.toml
  cstrml/staking/src/mock.rs
  cstrml/swork/Cargo.toml
  cstrml/swork/src/mock.rs
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  node/src/service.rs
  primitives/Cargo.toml
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/Cargo.toml
  runtime/src/impls.rs
  runtime/src/lib.rs
  runtime/src/weights/mod.rs
  runtime/src/weights/pallet_balances.rs
  runtime/src/weights/pallet_collective.rs
  runtime/src/weights/pallet_scheduler.rs
  runtime/src/weights/pallet_treasury.rs
Labels: A4-enhancement

#266 [MPoW] Fix A/B upgrade
  cstrml/swork/src/lib.rs
  cstrml/swork/src/mock.rs
  cstrml/swork/src/tests.rs
Labels: I1-panic 😱
