Repository crustio/crust, pull requests merged in 2020-10, with the labels that each got.

#267 [DSM] New payment and punishment menchanism
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  cstrml/market/src/lib.rs
  cstrml/market/src/mock.rs
  cstrml/market/src/tests.rs
  cstrml/payment/Cargo.toml
  cstrml/payment/src/lib.rs
  cstrml/payment/src/mock.rs
  cstrml/payment/src/tests.rs
  cstrml/swork/src/lib.rs
  cstrml/swork/src/mock.rs
  cstrml/swork/src/tests.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: A2-breakapi, A3-breaktest, M0-protocol, P1-asap🏃🏼‍♂️

#271 [MPoW] Fix files transition check
  cstrml/swork/src/lib.rs
Labels: I2-bug 🐜, M0-protocol

#272 [MPoW] Add maximum bonds restriction
  Cargo.lock
  cstrml/market/src/mock.rs
  cstrml/staking/Cargo.toml
  cstrml/staking/src/mock.rs
  cstrml/swork/src/lib.rs
  cstrml/swork/src/mock.rs
  cstrml/swork/src/tests.rs
  runtime/src/lib.rs
Labels: A4-enhancement

#273 [Upgrade] Merge back poc-8.x versions
  .github/workflows/rust.yml
  Cargo.lock
  cstrml/candy/Cargo.toml
  cstrml/candy/src/lib.rs
  cstrml/staking/src/lib.rs
  node/res/rocky.json
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: A4-enhancement, M2-nicetohave
