Repository crustio/crust, pull requests merged in 2020-06, with the labels that each got.

#152 [Payment] Refactoring code structure and fix start delayed pay bug
  cstrml/market/src/lib.rs
  cstrml/market/src/mock.rs
  cstrml/market/src/tests.rs
  cstrml/payment/src/lib.rs
  cstrml/payment/src/mock.rs
  cstrml/payment/src/tests.rs
  cstrml/staking/src/mock.rs
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  cstrml/tee/src/tests.rs
  runtime/src/lib.rs
Labels: enhancement, maxwell🐜, pleasereview

#154 [Market] Fix duplicate file and register again
  cstrml/market/src/lib.rs
  cstrml/market/src/tests.rs
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  cstrml/tee/src/tests.rs
Labels: maxwell🐜, pleasereview

#157 [Others] Add sudo module and prepping version
  Cargo.lock
  cstrml/market/Cargo.toml
  cstrml/payment/Cargo.toml
  cstrml/staking/Cargo.toml
  cstrml/staking/src/lib.rs
  cstrml/tee/Cargo.toml
  node/Cargo.toml
  node/src/chain_spec.rs
  primitives/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  scripts/build-only-wasm.sh
Labels: maxwell

#169 [Market+GPoS+Balance] Add transferrable_balance into balance module
  .github/workflows/rust.yml
  Cargo.lock
  cstrml/balances/Cargo.toml
  cstrml/balances/src/benchmarking.rs
  cstrml/balances/src/lib.rs
  cstrml/balances/src/tests.rs
  cstrml/balances/src/tests_composite.rs
  cstrml/balances/src/tests_local.rs
  cstrml/market/Cargo.toml
  cstrml/market/src/lib.rs
  cstrml/market/src/tests.rs
  cstrml/payment/Cargo.toml
  cstrml/staking/Cargo.toml
  cstrml/staking/src/lib.rs
  cstrml/tee/Cargo.toml
  primitives/Cargo.toml
  primitives/src/lib.rs
  primitives/src/traits.rs
  runtime/Cargo.toml
Labels: maxwell🐜, p0

#171 [MPoW] New TEE register
  Cargo.lock
  cstrml/market/src/mock.rs
  cstrml/payment/src/mock.rs
  cstrml/staking/src/mock.rs
  cstrml/tee/Cargo.toml
  cstrml/tee/src/api.rs
  cstrml/tee/src/lib.rs
  cstrml/tee/src/mock.rs
  cstrml/tee/src/tests.rs
  node/src/chain_spec.rs
  primitives/src/lib.rs
Labels: breaksapi, breaksconsensus, maxwell, p0, pleasereview

#172 [MPoW] Add set enclave code
  cstrml/staking/src/lib.rs
  cstrml/tee/src/lib.rs
Labels: maxwell, p0, pleasereview

#175 [Payment] Replace force transfer with currency's transfer
  cstrml/payment/src/lib.rs
  cstrml/payment/src/mock.rs
  runtime/src/lib.rs
Labels: maxwell, pleasereview
