Repository crustio/crust, pull requests merged in 2021-02, with the labels that each got.

#468 [Claims] Add superior and claim limitation on mint
  cstrml/claims/src/lib.rs
  cstrml/claims/src/tests.rs
Labels: need-cherry-block🍒

#469 [Runtime] Adjust some settings
  runtime/src/lib.rs
Labels: need-cherry-block🍒

#473 [GPoS] Market pot should reward authoring as well
  cstrml/staking/src/lib.rs
  cstrml/staking/src/mock.rs
  cstrml/staking/src/tests.rs
  runtime/src/lib.rs
Labels: need-cherry-block🍒

#479 [Candy + Claims] Move bond eth from candy to claims
  Cargo.lock
  cstrml/candy/Cargo.toml
  cstrml/candy/src/lib.rs
  cstrml/claims/src/lib.rs
  cstrml/claims/src/tests.rs
Labels: I6-enhancement 🎁

#482 Fix guarantor unbond
  cstrml/staking/src/lib.rs
Labels: I1-panic 😱, P0-dropeverything🔔, need-cherry-block🍒

#487 [GPoS] Fix guarantor unbond bug
  cstrml/staking/src/lib.rs
  cstrml/staking/src/tests.rs
Labels: I1-panic 😱

#501 [Market] Optimize some events
  cstrml/market/src/lib.rs
Labels: need-cherry-block🍒

#504 [Docs] Fix README
  README.md
Labels: A4-enhancement

#507 [DSM] Support market switch for plage_storage_order
  cstrml/market/src/lib.rs
  cstrml/market/src/mock.rs
  cstrml/market/src/tests.rs
Labels: need-cherry-block🍒
